### ISSUE TITLE
gmp library linking error in Makefile

### ISSUE THREAD

**Issue by eckucukoglu** [MrJoy/ssss#5]
On line 8 of Makefile, cc should take -lgmp option later than source code.

Otherwise undefined reference error can occur.
```
/tmp/ccDyHO5q.o: In function `field_init':
ssss.c:(.text+0x1a8): undefined reference to `__gmpz_init_set_ui'
ssss.c:(.text+0x1b5): undefined reference to `__gmpz_setbit'
...
```
[Related note](http://stackoverflow.com/a/11894098)

**Comment by MrJoy** [comment]
Interesting.  This begs the question of how this ever worked. :-?
