### ISSUE TITLE
Use /dev/urandom as recommended (and for significant speedup)

### ISSUE THREAD

**Issue by sigio** [MrJoy/ssss#9]
It's recommended to use /dev/urandom on systems that have it (and at least on linux and *bsd)

See also this article:
http://www.2uo.de/myths-about-urandom/

Using /dev/urandom makes ssss-split significantly faster

**Comment by MrJoy** [comment]
As I have zero cryptographic expertise, I've reached out to the author of SSSS for clarification on whether this change is in fact safe to make in this context.  That article seems quite compelling on its face, but I'm not qualified to validate it.  I'll update this ticket if/when I hear back from him.

**Comment by sigio** [comment]
Seems https://github.com/dren-dk/SSSS already does this as well.

**Comment by MrJoy** [comment]
Ooh.  I should look that over for useful bits and pieces.  In the meantime, if you're in dire need, that fork seems like a perfectly cromulant fork to use!

**Comment by sigio** [comment]
no problem. I had already created a locally forked version which I patched.
just wanted to get this somewhat closer to upstream. Also filed a wishlist bug against the debian package of ssss to change to /dev/urandom

**Comment by MrJoy** [comment]
Sorry for the delay!  Fix is applied here.
